	
var yaoci_chu = [
'潛龍勿用',
'履霜堅冰至',
'磐桓利居貞利建侯',
'發蒙利用刑人用說桎梏以往吝',
'需于郊利用恆无咎',
'不永所事小有言終吉',
'師出以律否臧凶',
'有孚比之无咎有孚盈缶終來有它吉',
'復自道何其咎吉',
'素履往无咎',
'拔茅茹以其彙征吉',
'拔茅茹以其彙貞吉亨',
'同人于門无咎',
'无交害匪咎艱則无咎',
'謙謙君子用涉大川吉',
'鳴豫凶',
'官有渝貞吉出門交有功',
'幹父之蠱有子考无咎厲終吉',
'咸臨貞吉',
'童觀小人无咎君子吝',
'屨校滅趾无咎',
'賁其趾舍車而徒',
'剝床以足蔑貞凶',
'不遠復无祇悔元吉',
'无妄往吉',
'有厲利已',
'舍爾靈龜觀我朵頤凶',
'藉用白茅无咎',
'習坎入于坎窞凶',
'履錯然敬之无咎',
'咸其拇',
'浚恒貞凶无攸利',
'遯尾厲勿用有攸往',
'壯于趾征凶有孚',
'晉如摧如貞吉罔孚裕无咎',
'明夷于飛垂其翼君子于行三日不食有攸往主人有言',
'閑有家悔亡',
'悔亡喪馬勿逐自復見惡人无咎',
'往蹇來譽',
'无咎',
'已事遄往无咎酌損之',
'利用為大作元吉无咎',
'壯于前趾往不勝為咎',
'繫于金柅貞吉有攸往見凶羸豕孚蹢躅',
'有孚不終乃亂乃萃若號一握為笑勿恤往无咎',
'允升大吉',
'臀困于株木入于幽谷三歲不覿',
'井泥不食舊井无禽',
'鞏用黃牛之革',
'鼎顛趾利出否得妾以其子无咎',
'震來虩虩後笑言啞啞吉',
'艮其趾无咎利永貞',
'鴻漸于干小子厲有言无咎',
'歸妹以娣跛能履征吉',
'遇其配主雖旬无咎往有尚',
'旅瑣瑣斯其所取災',
'進退利武人之貞',
'和兌吉',
'用拯馬壯吉',
'不出戶庭无咎',
'虞吉有它不燕',
'飛鳥以凶',
'曳其輪濡其尾无咎',
'濡其尾吝'];

var yaoci_er = [
'見龍在田利見大人','直方大不習无不利','屯如邅如乘馬班如匪寇婚媾女子貞不字十年乃字','包蒙吉納婦吉子克家','需于沙小有言終吉','不克訟歸而逋其邑人三百戶无眚','在師中吉无咎王三錫命','比之自內貞吉','牽復吉','履道坦坦幽人貞吉','包荒用馮河不遐遺朋亡得尚于中行','包承小人吉大人否亨','同人于宗吝','大車以載有攸往无咎','鳴謙貞吉','介于石不終日貞吉','係小子失丈夫','幹母之蠱不可貞','咸臨吉无不利','闚觀利女貞','噬膚滅鼻无咎','賁其須','剝床以辨蔑貞凶','休復吉','不耕穫不菑畬則利有攸往','輿說輹','顛頤拂經于丘頤征凶','枯楊生稊老夫得其女妻无不利','坎有險求小得','黃離元吉','咸其腓凶居吉','悔亡','執之用黃牛之革莫之勝說','貞吉','晉如愁如貞吉受茲介福于其王母','明夷夷于左股用拯馬壯吉','无攸遂在中饋貞吉','遇主于巷无咎','王臣蹇蹇匪躬之故','田獲三狐得黃矢貞吉','利貞征凶弗損益之','或益之十朋之龜弗克違永貞吉王用享于帝吉','惕號莫夜有戎勿恤','包有魚无咎不利賓',
'引吉无咎孚乃利用禴','孚乃利用禴无咎','困于酒食朱紱方來利用享祀征凶无咎',
'井谷射鮒甕敝漏','已日乃革之征吉无咎','鼎有實我仇有疾不我能即吉','震來厲億喪貝躋于九陵勿逐七日得','艮其腓不拯其隨其心不快','鴻漸于磐飲食衎衎吉','眇能視利幽人之貞','豐其蔀日中見斗往得疑疾有孚發若吉','旅即次懷其資得童僕貞','巽在床下用史巫紛若吉无咎','孚兌吉悔亡','渙奔其机悔亡','不出門庭凶','鶴鳴在陰其子和之我有好爵吾與爾靡之',
'過其祖遇其妣不及其君遇其臣无咎','婦喪其茀勿逐七日得','曳其輪貞吉'
]

var yaoci_san=[
'君子終日乾乾夕惕若厲无咎','含章可貞或從王事无成有終','即鹿无虞惟入于林中君子幾不如舍往吝','勿用取女見金夫不有躬无攸利','需于泥致寇至','食舊德貞厲終吉或從王事无成','師或輿尸凶','比之匪人','輿說輻夫妻反目','眇能視跛能履履虎尾咥人凶武人為于大君','无平不陂无往不復艱貞无咎勿恤其孚于食有福','包羞','伏戎于莽升其高陵三歲不興','公用亨于天子小人弗克','勞謙君子有終吉','盱豫悔遲有悔','係丈夫失小子隨有求得利居貞','幹父之蠱小有悔无大咎','甘臨无攸利既憂之无咎','觀我生進退','噬腊肉遇毒小吝无咎','賁如濡如永貞吉','剝之无咎','頻復厲无咎','无妄之災或繫之牛行人之得邑人之災','良馬逐利艱貞曰閑輿衛利有攸往','拂頤貞凶十年勿用无攸利','棟橈凶','來之坎坎險且枕入于坎窞勿用','日昃之離不鼓缶而歌則大耋之嗟凶','咸其股執其隨往吝','不恒其德或承之羞貞吝','係遯有疾厲畜臣妾吉','小人用壯君子用罔貞厲羝羊觸藩羸其角','眾允悔亡','明夷于南狩得其大首不可疾貞','家人嗃嗃悔厲吉婦子嘻嘻終吝','見輿曳其牛掣其人天且劓无初有終','往蹇來反','負且乘致寇至貞吝','三人行則損一人一人行則得其友','益之用凶事无咎有孚中行告公用圭','壯于頄有凶君子夬夬獨行遇雨若濡有慍无咎','臀无膚其行次且厲无大咎','萃如嗟如无攸利往无咎小吝','升虛邑','困于石據于蒺蔾入于其宮不見其妻凶','井渫不食為我心惻可用汲王明並受其福','征凶貞厲革言三就有孚','鼎耳革其行塞雉膏不食方雨虧悔終吉','震蘇蘇震行无眚','艮其限列其夤厲薰心','鴻漸于陸夫征不復婦孕不育凶利禦寇','歸妹以須反歸以娣','豐其沛日中見沬折其右肱无咎','旅焚其次喪其童僕貞厲','頻巽吝','來兌凶','渙其躬无悔','不節若則嗟若无咎','得敵或鼓或罷或泣或歌','弗過防之從或戕之凶','高宗伐鬼方三年克之小人勿用','未濟征凶利涉大川'
]

var yaoci_si = ['或躍在淵无咎','括囊无咎无譽','乘馬班如求婚媾往吉无不利','困蒙吝','需于血出自穴','不克訟復即命渝安貞吉','師左次无咎','外比之貞吉','有孚血去惕出无咎','履虎尾愬愬終吉','翩翩不富以其鄰不戒以孚','有命无咎疇離祉','乘其墉弗克攻吉','匪其彭无咎','无不利撝謙','由豫大有得勿疑朋盍簪','隨有獲貞凶有孚在道以明何咎','裕父之蠱往見吝','至臨无咎','觀國之光利用賓于王','噬乾胏得金矢利艱貞吉','賁如皤如白馬翰如匪寇婚媾','剝床以膚凶','中行獨復','可貞无咎','童牛之牿元吉','顛頤吉虎視眈眈其欲逐逐无咎','棟隆吉有它吝','樽酒簋貳用缶納約自牖終无咎','突如其來如焚如死如棄如','貞吉悔亡憧憧往來朋從爾思','田无禽','好遯君子吉小人否','貞吉悔亡藩決不羸壯于大輿之輹','晉如鼫鼠貞厲','入于左腹獲明夷之心于出門庭','富家大吉','睽孤遇元夫交孚厲无咎','往蹇來連','解而拇朋至斯孚','損其疾使遄有喜无咎','中行告公從利用為依遷國','臀无膚其行次且牽羊悔亡聞言不信','包无魚起凶','大吉无咎','王用亨于岐山吉无咎','來徐徐困于金車吝有終','井甃无咎','悔亡有孚改命吉','鼎折足覆公餗其形渥凶','震遂泥','艮其身无咎','鴻漸于木或得其桷无咎','歸妹愆期遲歸有時','豐其蔀日中見斗遇其夷主吉','旅于處得其資斧我心不快','悔亡田獲三品','商兌未寧介疾有喜','渙其群元吉渙有丘匪夷所思','安節亨','月幾望馬匹亡无咎','无咎弗過遇之往厲必戒勿用永貞','繻有衣袽終日戒','貞吉悔亡震用伐鬼方三年有賞于大國'
]

var yaoci_wu = [
'飛龍在天利見大人','黃裳元吉','屯其膏小貞吉大貞凶','童蒙吉','需于酒食貞吉','訟元吉','田有禽利執言无咎長子帥師弟子輿尸貞凶','顯比王用三驅失前禽邑人不誡吉','有孚攣如富以其鄰','夬履貞厲','帝乙歸妹以祉元吉','休否大人吉其亡其亡繫于苞桑','同人先號咷而後笑大師克相遇','厥孚交如威如吉','不富以其鄰利用侵伐无不利','貞疾恒不死','孚于嘉吉','幹父之蠱用譽','知臨大君之宜吉','觀我生君子无咎','噬乾肉得黃金貞厲无咎','賁于丘園束帛戔戔吝終吉','貫魚以宮人寵无不利','敦復无悔','无妄之疾勿藥有喜','豶豕之牙吉','拂經居貞吉不可涉大川','枯楊生華老婦得其士夫无咎无譽','坎不盈祗既平无咎','出涕沱若戚嗟若吉','咸其脢无悔','恒其德貞婦人吉夫子凶','嘉遯貞吉','喪羊于易无悔','悔亡失得勿恤往吉无不利','箕子之明夷利貞','王假有家勿恤吉','悔亡厥宗噬膚往何咎','大蹇朋來','君子維有解吉有孚于小人','或益之十朋之龜弗克違元吉','有孚惠心勿問元吉有孚惠我德','莧陸夬夬中行无咎','以杞包瓜含章有隕自天','萃有位无咎匪孚元永貞悔亡','貞吉升階','劓刖困于赤紱乃徐有說利用祭祀','井洌寒泉食','大人虎變未占有孚','鼎黃耳金鉉利貞','震往來厲意无喪有事','艮其輔言有序悔亡','鴻漸于陵婦三歲不孕終莫之勝吉','帝乙歸妹其君之袂不如其娣之袂良月幾望吉','來章有慶譽吉','射雉一矢亡終以譽命','貞吉悔亡无不利无初有終先庚三日後庚三日吉','孚于剝有厲','渙汗其大號渙王居无咎','甘節吉往有尚','有孚攣如无咎','密雲不雨自我西郊公弋取彼在穴','東鄰殺牛不如西鄰之禴祭實受其福','貞吉无悔君子之光有孚吉'
]

var yaoci_shang = [
'亢龍有悔','龍戰于野其血玄黃','乘馬班如泣血漣如','擊蒙不利為寇利禦寇','入于穴有不速之客三人來敬之終吉','或錫之鞶帶終朝三褫之','大君有命開國承家小人勿用','比之无首凶','既雨既處尚德載婦貞厲月幾望君子征凶','視履考祥其旋元吉','城復于隍勿用師自邑告命貞吝','傾否先否後喜','同人于郊无悔','自天祐之吉无不利','鳴謙利用行師征邑國','冥豫成有渝无咎','拘係之乃從維之王用亨于西山','不事王侯高尚其事','敦臨吉无咎','觀其生君子无咎','何校滅耳凶','白賁无咎','碩果不食君子得輿小人剝廬','迷復凶有災眚用行師終有大敗以其國君凶至于十年不克征','无妄行有眚无攸利','何天之衢亨','由頤厲吉利涉大川','過涉滅頂凶无咎','係用黴纆寘于叢棘三歲不得凶','王用出征有嘉折首獲匪其醜无咎','咸其輔頰舌','振恒凶','肥遯无不利','羝羊觸藩不能退不能遂无攸利艱則吉','晉其角維用伐邑厲吉无咎貞吝','不明晦初登于天後入于地','有孚威如終吉','睽孤見豕負塗載鬼一車先張之弧後說之弧匪寇婚媾往遇雨則吉','往蹇來碩吉利見大人','公用射隼于高墉之上獲之无不利','弗損益之无咎貞吉利有攸往得臣无家','莫益之或擊之立心勿恆凶','无號終有凶','姤其角吝无咎','齎咨涕洟无咎','冥升利于不息之貞','困于葛藟于臲卼曰動悔有悔征吉','井收勿幕有孚元吉','君子豹變小人革面征凶居貞吉','鼎玉鉉大吉无不利','震索索視矍矍征凶震不于其躬于其鄰无咎婚媾有言','敦艮吉','鴻漸于陸其羽可用為儀吉','女承筐无實士刲羊无血无攸利','豐其屋蔀其家闚其戶闃其无人三歲不覿凶','鳥焚其巢旅人先笑後號咷喪牛于易凶','巽在床下喪其資斧貞凶','引兌','渙其血去逖出无咎','苦節貞凶悔亡','翰音登于天貞凶','弗遇過之飛鳥離之凶是謂災眚','濡其首厲','有孚于飲酒无咎濡其首有孚失是'
]

var yaociAll = [yaoci_chu,yaoci_er,yaoci_san,yaoci_si,yaoci_wu,yaoci_shang]

//吉<=>无咎
var jw = [
 {number:2,  firstPos:4,secondPos:5},
 {number:5,  firstPos:1,secondPos:2},
 {number:7,  firstPos:2,secondPos:2},
 {number:8,  firstPos:1,secondPos:1},
 {number:9,  firstPos:2,secondPos:4},
 {number:10,  firstPos:1,secondPos:2},
 {number:11,  firstPos:1,secondPos:3},
 {number:11,  firstPos:3,secondPos:5},
 {number:12,  firstPos:2,secondPos:4},
 {number:12,  firstPos:4,secondPos:5},
 {number:13,  firstPos:1,secondPos:4},
 {number:14,  firstPos:4,secondPos:5},
 {number:16,  firstPos:2,secondPos:6},
 {number:19,  firstPos:2,secondPos:3},
 {number:19,  firstPos:4,secondPos:5},
 {number:19,  firstPos:6,secondPos:6},
 {number:21,  firstPos:3,secondPos:4},
 {number:21,  firstPos:4,secondPos:5},
 {number:22,  firstPos:5,secondPos:6},
 {number:24,  firstPos:2,secondPos:3},
 {number:25,  firstPos:1,secondPos:4},
 {number:28,  firstPos:4,secondPos:5},
 {number:30,  firstPos:1,secondPos:2},
 {number:30,  firstPos:5,secondPos:6},
 {number:35,  firstPos:1,secondPos:1},
 // {number:35,  firstPos:1,secondPos:2},
 {number:35,  firstPos:5,secondPos:6},
 {number:38,  firstPos:4,secondPos:6},
 {number:40,  firstPos:1,secondPos:2},
 {number:41,  firstPos:4,secondPos:5},
 {number:41,  firstPos:5,secondPos:6},
 {number:41,  firstPos:6,secondPos:6},
 {number:42,  firstPos:1,secondPos:1},
 // {number:42,  firstPos:1,secondPos:2},
 {number:45,  firstPos:3,secondPos:4},
 {number:45,  firstPos:4,secondPos:4},
 {number:46,  firstPos:1,secondPos:2},
 {number:46,  firstPos:2,secondPos:4},
 {number:46,  firstPos:4,secondPos:4},
 {number:46,  firstPos:4,secondPos:5},
 {number:48,  firstPos:4,secondPos:6},
 {number:49,  firstPos:2,secondPos:2},
 {number:50,  firstPos:1,secondPos:2},
 {number:53,  firstPos:1,secondPos:2},
 {number:53,  firstPos:4,secondPos:5},
 {number:55,  firstPos:1,secondPos:2},
 {number:55,  firstPos:2,secondPos:3},
 {number:57,  firstPos:2,secondPos:2},
 {number:59,  firstPos:4,secondPos:5},
 {number:60,  firstPos:3,secondPos:5},
 {number:61,  firstPos:1,secondPos:4},
 {number:64,  firstPos:5,secondPos:6},
]

//凶<=>吉
var jx = [
	{number:3,  firstPos:5,secondPos:5},
	{number:7,  firstPos:1,secondPos:2},
	{number:8,  firstPos:5,secondPos:6},
	{number:10,  firstPos:2,secondPos:3},
	{number:10,  firstPos:3,secondPos:4},
	{number:16,  firstPos:1,secondPos:2},
	{number:17,  firstPos:1,secondPos:4},
	{number:17,  firstPos:4,secondPos:5},
	{number:27,  firstPos:3,secondPos:4},
	{number:28,  firstPos:3,secondPos:4},
	{number:30,  firstPos:2,secondPos:3},
	{number:30,  firstPos:3,secondPos:5},
	{number:31,  firstPos:2,secondPos:2},
	{number:32,  firstPos:1,secondPos:5},
	{number:32,  firstPos:5,secondPos:5},
	{number:34,  firstPos:1,secondPos:2},
	{number:41,  firstPos:2,secondPos:6},
	{number:42,  firstPos:2,secondPos:3},
	{number:42,  firstPos:5,secondPos:6},
	{number:44,  firstPos:1,secondPos:1},
	{number:47,  firstPos:3,secondPos:6},
	{number:49,  firstPos:3,secondPos:4},
	{number:49,  firstPos:4,secondPos:6},
	{number:50,  firstPos:3,secondPos:4},
	{number:50,  firstPos:4,secondPos:6},
	{number:51,  firstPos:1,secondPos:6},
	{number:53,  firstPos:2,secondPos:3},
	{number:55,  firstPos:5,secondPos:6},
	{number:57,  firstPos:5,secondPos:6},
	{number:58,  firstPos:2,secondPos:3},
	{number:60,  firstPos:5,secondPos:6},
	{number:64,  firstPos:2,secondPos:3},
	{number:64,  firstPos:3,secondPos:4},
]	

//凶<=>无咎
var xw = [
	{number:7,  firstPos:2,secondPos:3},
	{number:7,  firstPos:5,secondPos:5},
	{number:9,  firstPos:4,secondPos:6},
	{number:21,  firstPos:6,secondPos:6},
	{number:23,  firstPos:2,secondPos:3},
	{number:23,  firstPos:3,secondPos:4},
	{number:24,  firstPos:3,secondPos:6},
	{number:28,  firstPos:1,secondPos:3},
	{number:28,  firstPos:5,secondPos:6},
	{number:28,  firstPos:6,secondPos:6},
	{number:29,  firstPos:1,secondPos:4},
	{number:41,  firstPos:1,secondPos:2},
	{number:41,  firstPos:2,secondPos:4},
	{number:42,  firstPos:3,secondPos:3},
	{number:42,  firstPos:3,secondPos:6},
	{number:43,  firstPos:3,secondPos:3},
	{number:43,  firstPos:5,secondPos:6},
	{number:44,  firstPos:1,secondPos:2},
	{number:44,  firstPos:2,secondPos:4},
	{number:44,  firstPos:4,secondPos:6},
	{number:47,  firstPos:2,secondPos:2},
	{number:47,  firstPos:3,secondPos:2},
	{number:49,  firstPos:2,secondPos:3},
	{number:51,  firstPos:6,secondPos:6},
	// {number:52,  firstPos:4,secondPos:6},
	{number:53,  firstPos:3,secondPos:4},
	{number:55,  firstPos:3,secondPos:6},
	{number:60,  firstPos:1,secondPos:2},
	{number:60,  firstPos:2,secondPos:3},
	{number:61,  firstPos:5,secondPos:6},
	{number:62,  firstPos:1,secondPos:2},
	{number:62,  firstPos:2,secondPos:3},
	{number:62,  firstPos:3,secondPos:4},
	{number:62,  firstPos:4,secondPos:6},
]
//the 
var allTransitions = [jw,jx,xw]